import { Octokit } from "@octokit/rest";
import { z } from "zod";
import { AppError } from "@/shared/errors.ts";
import { env } from "@/config/env.ts";
import { logger } from "@/shared/logger.ts";
import type { Task } from "@/modules/tasks/tasks.schema.ts";

const log = logger.child("github");

export const CreateIssueSchema = z.object({
  repo: z.string().regex(/^[\w.-]+\/[\w.-]+$/, "Expected owner/repo"),
  title: z.string().min(1),
  body: z.string().default(""),
  labels: z.array(z.string()).optional(),
});
export type CreateIssueInput = z.infer<typeof CreateIssueSchema>;

export const SyncProjectIssuesSchema = z.object({
  repo: z
    .string()
    .regex(/^[\w.-]+\/[\w.-]+$/, "Expected owner/repo")
    .optional(),
});
export type SyncProjectIssuesInput = z.infer<typeof SyncProjectIssuesSchema>;

export const ReviewCodeSchema = z.object({
  repo: z.string().regex(/^[\w.-]+\/[\w.-]+$/),
  pullNumber: z.number().int().positive(),
});
export type ReviewCodeInput = z.infer<typeof ReviewCodeSchema>;

export interface GitHubConfig {
  token: string;
  defaultRepo: string;
}

export interface CreatedIssue {
  url: string;
  number: number;
}

export interface SyncResult {
  repo: string;
  created: number;
  skipped: number;
  issues: { taskId: string; url: string; number: number }[];
}

export interface GitHubIntegration {
  configure(cfg: Partial<GitHubConfig>): void;
  getConfig(): { enabled: boolean; hasToken: boolean; defaultRepo: string };
  createIssue(input: CreateIssueInput): Promise<CreatedIssue>;
  syncProjectTasks(
    projectId: string,
    projectName: string,
    idea: string,
    repo: string,
    tasks: Task[],
    onTaskLinked: (taskId: string, issue: CreatedIssue) => Promise<void>,
  ): Promise<SyncResult>;
  reviewCode(input: ReviewCodeInput): Promise<{ summary: string; comments: string[] }>;
}

function parseRepo(repo: string): { owner: string; repo: string } {
  const [owner, name] = repo.split("/");
  if (!owner || !name) throw AppError.badRequest("Invalid repo format, expected owner/repo");
  return { owner, repo: name };
}

function taskLabels(task: Task): string[] {
  return ["founderos", task.module, `priority:${task.priority}`].filter(Boolean);
}

function taskBody(task: Task, projectName: string, idea: string): string {
  return [
    task.description,
    "",
    "---",
    `_Generated by [FounderOS](https://github.com) · Project: **${projectName}**_`,
    "",
    `> ${idea}`,
    "",
    `- **Module:** ${task.module}`,
    `- **Priority:** ${task.priority}`,
    `- **Estimate:** ${task.estimate || "n/a"}`,
  ].join("\n");
}

export class GitHubService implements GitHubIntegration {
  private token = env.GITHUB_TOKEN ?? "";
  private defaultRepo = "";

  configure(cfg: Partial<GitHubConfig>): void {
    if (cfg.token !== undefined) this.token = cfg.token;
    if (cfg.defaultRepo !== undefined) this.defaultRepo = cfg.defaultRepo;
  }

  getConfig(): { enabled: boolean; hasToken: boolean; defaultRepo: string } {
    const hasToken = Boolean(this.token.trim());
    return { enabled: hasToken, hasToken, defaultRepo: this.defaultRepo };
  }

  private client(): Octokit {
    if (!this.token.trim()) {
      throw AppError.badRequest(
        "GitHub token not configured. Add GITHUB_TOKEN in .env or Settings → GitHub.",
      );
    }
    return new Octokit({ auth: this.token });
  }

  async createIssue(input: CreateIssueInput): Promise<CreatedIssue> {
    const octokit = this.client();
    const { owner, repo } = parseRepo(input.repo);
    try {
      const res = await octokit.rest.issues.create({
        owner,
        repo,
        title: input.title,
        body: input.body,
        labels: input.labels,
      });
      return { url: res.data.html_url, number: res.data.number };
    } catch (e) {
      log.error("create_issue_failed", { repo: input.repo, message: String(e) });
      throw AppError.upstream(`GitHub create issue failed: ${formatGhError(e)}`);
    }
  }

  async syncProjectTasks(
    projectId: string,
    projectName: string,
    idea: string,
    repo: string,
    tasks: Task[],
    onTaskLinked: (taskId: string, issue: CreatedIssue) => Promise<void>,
  ): Promise<SyncResult> {
    const pending = tasks.filter((t) => !t.githubIssueUrl);
    const result: SyncResult = { repo, created: 0, skipped: tasks.length - pending.length, issues: [] };

    for (const task of pending) {
      const issue = await this.createIssue({
        repo,
        title: `[${task.module}] ${task.title}`,
        body: taskBody(task, projectName, idea),
        labels: taskLabels(task),
      });
      await onTaskLinked(task.id, issue);
      result.issues.push({ taskId: task.id, url: issue.url, number: issue.number });
      result.created++;
      log.info("task_synced", { projectId, taskId: task.id, issue: issue.number });
    }

    return result;
  }

  async reviewCode(input: ReviewCodeInput): Promise<{ summary: string; comments: string[] }> {
    const octokit = this.client();
    const { owner, repo } = parseRepo(input.repo);

    try {
      const [pr, files] = await Promise.all([
        octokit.rest.pulls.get({ owner, repo, pull_number: input.pullNumber }),
        octokit.rest.pulls.listFiles({ owner, repo, pull_number: input.pullNumber, per_page: 100 }),
      ]);

      const fileSummary = files.data
        .slice(0, 30)
        .map((f) => `- \`${f.filename}\` (+${f.additions}/-${f.deletions})`)
        .join("\n");

      const summary = [
        `**${pr.data.title}** (#${input.pullNumber})`,
        pr.data.body?.slice(0, 500) ?? "",
        "",
        `**Changed files (${files.data.length}):**`,
        fileSummary,
      ].join("\n");

      const comments: string[] = [];
      for (const file of files.data.slice(0, 10)) {
        if (file.patch && file.patch.length < 2000) {
          comments.push(`Review \`${file.filename}\`: ${file.changes} changes (${file.status})`);
        }
      }

      // Post a summary comment on the PR.
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: input.pullNumber,
        body: `## FounderOS code review\n\n${summary}\n\n_Automated review — configure an LLM for deeper analysis in a future release._`,
      });

      return { summary, comments };
    } catch (e) {
      log.error("review_failed", { repo: input.repo, pull: input.pullNumber, message: String(e) });
      throw AppError.upstream(`GitHub PR review failed: ${formatGhError(e)}`);
    }
  }

  resolveRepo(explicit?: string): string {
    const repo = explicit?.trim() || this.defaultRepo.trim();
    if (!repo) {
      throw AppError.badRequest(
        "GitHub repo required (owner/repo). Set a default in Settings or pass repo in the request.",
      );
    }
    return repo;
  }
}

function formatGhError(e: unknown): string {
  if (e && typeof e === "object" && "message" in e) return String((e as { message: string }).message);
  return String(e);
}
