import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, ArrowLeft, Github, ExternalLink, Loader2 } from "lucide-react";
import { api } from "@/lib/api";
import { PageHeader } from "@/components/PageHeader";
import { ProjectSelect } from "@/components/ProjectSelect";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Task } from "@/lib/types";

const COLUMNS: { key: Task["status"]; label: string }[] = [
  { key: "todo", label: "To Do" },
  { key: "in_progress", label: "In Progress" },
  { key: "done", label: "Done" },
];

const next: Record<Task["status"], Task["status"] | null> = {
  todo: "in_progress",
  in_progress: "done",
  done: null,
};
const prev: Record<Task["status"], Task["status"] | null> = {
  todo: null,
  in_progress: "todo",
  done: "in_progress",
};

const priorityVariant: Record<Task["priority"], "default" | "warning" | "secondary"> = {
  high: "default",
  medium: "warning",
  low: "secondary",
};

export function Tasks() {
  const queryClient = useQueryClient();
  const [projectId, setProjectId] = useState("");
  const [syncRepo, setSyncRepo] = useState("");
  const projects = useQuery({ queryKey: ["projects"], queryFn: api.listProjects });
  const githubSettings = useQuery({ queryKey: ["settings-github"], queryFn: api.getGitHubSettings });

  useEffect(() => {
    if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id);
  }, [projects.data, projectId]);

  const tasks = useQuery({
    queryKey: ["tasks", projectId],
    queryFn: () => api.getTasks(projectId),
    enabled: !!projectId,
  });

  const move = useMutation({
    mutationFn: ({ id, status }: { id: string; status: Task["status"] }) =>
      api.updateTask(id, { status }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["tasks", projectId] }),
  });

  const syncGitHub = useMutation({
    mutationFn: () => api.syncTasksToGitHub(projectId, syncRepo.trim() || undefined),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["tasks", projectId] });
      queryClient.invalidateQueries({ queryKey: ["projects"] });
    },
  });

  const list = tasks.data ?? [];
  const project = projects.data?.find((p) => p.id === projectId);
  const unsynced = list.filter((t) => !t.githubIssueUrl).length;
  const ghReady = githubSettings.data?.hasToken;

  return (
    <div>
      <PageHeader
        title="Tasks"
        subtitle="Development tasks auto-generated by the Engineer agent."
        action={<ProjectSelect value={projectId} onChange={setProjectId} className="w-56" />}
      />

      {list.length > 0 && (
        <div className="mb-4 flex flex-wrap items-end gap-2 rounded-lg border border-border/60 bg-card/30 p-3">
          <div className="min-w-[200px] flex-1">
            <label className="mb-1 block text-xs text-muted-foreground">GitHub repo (owner/repo)</label>
            <Input
              value={syncRepo}
              onChange={(e) => setSyncRepo(e.target.value)}
              placeholder={project?.githubRepo ?? githubSettings.data?.defaultRepo ?? "your-org/your-repo"}
              className="h-9"
            />
          </div>
          <Button
            onClick={() => syncGitHub.mutate()}
            disabled={!ghReady || !projectId || unsynced === 0 || syncGitHub.isPending}
          >
            {syncGitHub.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Github className="mr-2 h-4 w-4" />
            )}
            {unsynced === 0 ? "All synced" : `Sync ${unsynced} to GitHub`}
          </Button>
          {!ghReady && (
            <span className="text-xs text-amber-300">Configure GitHub token in Settings first.</span>
          )}
          {syncGitHub.isSuccess && syncGitHub.data && (
            <span className="text-xs text-emerald-400">
              Created {syncGitHub.data.created} issue(s) in {syncGitHub.data.repo}.
            </span>
          )}
          {syncGitHub.isError && (
            <span className="text-xs text-destructive">{(syncGitHub.error as Error).message}</span>
          )}
        </div>
      )}

      {list.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center text-sm text-muted-foreground">
            {projectId ? "No tasks yet. Run the agents for this project." : "Select a project."}
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {COLUMNS.map((col) => {
            const items = list.filter((t) => t.status === col.key);
            return (
              <div key={col.key} className="rounded-xl border border-border/60 bg-card/30 p-3">
                <div className="mb-3 flex items-center justify-between px-1">
                  <span className="text-sm font-semibold">{col.label}</span>
                  <Badge variant="secondary">{items.length}</Badge>
                </div>
                <div className="space-y-2">
                  {items.map((t) => (
                    <Card key={t.id}>
                      <CardContent className="p-3">
                        <div className="mb-1 flex items-start justify-between gap-2">
                          <span className="text-sm font-medium">{t.title}</span>
                          <Badge variant={priorityVariant[t.priority]}>{t.priority}</Badge>
                        </div>
                        <p className="mb-2 line-clamp-2 text-xs text-muted-foreground">{t.description}</p>
                        <div className="flex items-center justify-between">
                          <div className="flex flex-wrap items-center gap-2">
                            <Badge variant="outline">{t.module}</Badge>
                            <span className="text-xs text-muted-foreground">{t.estimate}</span>
                            {t.githubIssueUrl && (
                              <a
                                href={t.githubIssueUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                                onClick={(e) => e.stopPropagation()}
                              >
                                #{t.githubIssueNumber}
                                <ExternalLink className="h-3 w-3" />
                              </a>
                            )}
                          </div>
                          <div className="flex gap-1">
                            {prev[t.status] && (
                              <Button
                                size="icon"
                                variant="ghost"
                                className="h-7 w-7"
                                onClick={() => move.mutate({ id: t.id, status: prev[t.status]! })}
                              >
                                <ArrowLeft className="h-3.5 w-3.5" />
                              </Button>
                            )}
                            {next[t.status] && (
                              <Button
                                size="icon"
                                variant="ghost"
                                className="h-7 w-7"
                                onClick={() => move.mutate({ id: t.id, status: next[t.status]! })}
                              >
                                <ArrowRight className="h-3.5 w-3.5" />
                              </Button>
                            )}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
