-- FounderOS initial schema (Postgres + pgvector)
-- Embedding dimension defaults to 768 (Gemini text-embedding-004).

-- The `memories` table + pgvector setup are handled dynamically by the migrate
-- script (shared/db/migrate.ts) so the app runs with OR without pgvector.
-- gen_random_uuid() is built into Postgres 13+ (no pgcrypto needed).

-- Projects: one startup idea per project.
CREATE TABLE IF NOT EXISTS projects (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  idea        TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'draft',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Orchestration runs: one per pipeline execution.
CREATE TABLE IF NOT EXISTS runs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  status      TEXT NOT NULL DEFAULT 'pending',
  error       TEXT,
  started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_runs_project ON runs(project_id);

-- The consolidated startup plan produced by the agents.
CREATE TABLE IF NOT EXISTS startup_plans (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id           UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  run_id               UUID REFERENCES runs(id) ON DELETE SET NULL,
  market_analysis      JSONB,
  competitor_analysis  JSONB,
  opportunities        JSONB,
  mvp_features         JSONB,
  pricing_strategy     JSONB,
  financials           JSONB,
  architecture         JSONB,
  roadmap              JSONB,
  launch_plan          JSONB,
  review               JSONB,
  summary              TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_plans_project ON startup_plans(project_id);

-- Development tasks (generated by the Engineer agent).
CREATE TABLE IF NOT EXISTS tasks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  module      TEXT NOT NULL DEFAULT 'general',
  status      TEXT NOT NULL DEFAULT 'todo',
  priority    TEXT NOT NULL DEFAULT 'medium',
  estimate    TEXT NOT NULL DEFAULT '',
  position    INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);

-- Raw per-agent outputs for traceability/debugging.
CREATE TABLE IF NOT EXISTS agent_outputs (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  run_id      UUID REFERENCES runs(id) ON DELETE CASCADE,
  agent       TEXT NOT NULL,
  output      JSONB NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_agent_outputs_project ON agent_outputs(project_id);

-- Conversation log per project.
CREATE TABLE IF NOT EXISTS conversations (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  role        TEXT NOT NULL,
  content     TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_conversations_project ON conversations(project_id);

-- NOTE: the `memories` table (long-term vector memory) is created by the migrate
-- script, which picks a pgvector column when available and a JSONB fallback
-- otherwise. See shared/db/migrate.ts.
